### ISSUE TITLE
syntax wrong

### ISSUE THREAD

**Issue by irpcpro** [vitodtagliente/pure-routing#2]
https://github.com/vitodtagliente/pure-routing/blob/e1a7a655debaa0ba65214188ea7dba642a08da7f/Route.php#L33

hi. in this line of the code, for the is_subclass_of() function, the first argument of the function must be the class name which is extended from the Middleware::class

**it should change to this :**
`is_subclass_of($class_name, Middleware::class)`

for now, this line always returns false.
please change it on composer package manager. i'm using this package and it's very awesome ..

thanks ...

**Comment by vitodtagliente** [comment]
done, thank you!!
